language: java

jdk:
  - oraclejdk8
  
 install:
  bundle install -- path vendor/bundle
  npm install
  
 install: skip
 
 script: bundle exec thor build
 
 script:
  - bundle exec rake build
  - bundle exec rake builddoc
 script:
  - bundle exec rake build && bundle exec rake builddoc


script: ./scripts/run-tests.sh

 